#! /usr/bin/env python3


import argparse
import pysam
# from gtf_io import load_gtf_to_gene_data
# from flair.io_utils import make_temp_dir
# import networkx as nx
from copy import deepcopy
# import graphviz
import variant_processing as vp
from flair.pycbio.hgdata.bed import BedReader
from flair.flair_bed import FlairBed
from predictProductivity import translate_from_bed
from flair.isoform_data import make_big_bed, get_reverse_complement, COMPBASE


CODON_TABLE = {
    'ATA': 'I', 'ATC': 'I', 'ATT': 'I', 'ATG': 'M',
    'ACA': 'T', 'ACC': 'T', 'ACG': 'T', 'ACT': 'T',
    'AAC': 'N', 'AAT': 'N', 'AAA': 'K', 'AAG': 'K',
    'AGC': 'S', 'AGT': 'S', 'AGA': 'R', 'AGG': 'R',
    'CTA': 'L', 'CTC': 'L', 'CTG': 'L', 'CTT': 'L',
    'CCA': 'P', 'CCC': 'P', 'CCG': 'P', 'CCT': 'P',
    'CAC': 'H', 'CAT': 'H', 'CAA': 'Q', 'CAG': 'Q',
    'CGA': 'R', 'CGC': 'R', 'CGG': 'R', 'CGT': 'R',
    'GTA': 'V', 'GTC': 'V', 'GTG': 'V', 'GTT': 'V',
    'GCA': 'A', 'GCC': 'A', 'GCG': 'A', 'GCT': 'A',
    'GAC': 'D', 'GAT': 'D', 'GAA': 'E', 'GAG': 'E',
    'GGA': 'G', 'GGC': 'G', 'GGG': 'G', 'GGT': 'G',
    'TCA': 'S', 'TCC': 'S', 'TCG': 'S', 'TCT': 'S',
    'TTC': 'F', 'TTT': 'F', 'TTA': 'L', 'TTG': 'L',
    'TAC': 'Y', 'TAT': 'Y', 'TAA': '_', 'TAG': '_',
    'TGC': 'C', 'TGT': 'C', 'TGA': '_', 'TGG': 'W',
}

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--bam', required=True, type=str,
                        help="bam file (this is your primary bam input, required)")
    parser.add_argument('--norm_bam', type=str,
                        help="normal bam file (optional, used to call variants as somatic or not)")
    parser.add_argument('--vcf', required=True, type=str,
                        help="vcf file (even if you are inputting both normal and tumor bams, you can still provide a single vcf here)")
    parser.add_argument('--norm_vcf', type=str,
                        help="normal vcf file, optional even if providing a normal bam")
    parser.add_argument('-o', '--output', default='flair',
                        help="output prefix. default: 'flair'")
    parser.add_argument('-g', '--genome',
                        type=str, required=True, help='FastA of reference genome')
    # parser.add_argument('-f', '--gtf',
    #                     type=str, required=True,
    #                     help='GTF annotation file')
    parser.add_argument('--isoform_bed',
                        type=str, required=True,
                        help='isoform bed generated by FLAIR transcriptome')
    parser.add_argument('--read_map',
                        type=str, required=True,
                        help='read map for tumor/single sample by FLAIR transcriptome or flair quantify')
    parser.add_argument('--norm_read_map', type=str,
                        help='read map for normal (optional) sample by FLAIR transcriptome or flair quantify')
    parser.add_argument('--frac_support', default=0.05, type=float,
                        help='fraction of reads required to call allele, not recommended to change from default')
    parser.add_argument('--read_support', default=3, type=int,
                        help='number of reads required to call allele')
    parser.add_argument('--annotate_bams', default=False, action='store_true',
                        help='label reads in bam files with HP tags for allele groups')
    parser.add_argument('--generate_map', default=False, action='store_true',
                        help='output read map of allele groups to read names')
    # parser.add_argument('--keep_intermediate', default=False, action='store_true',
    #                     help='''specify if intermediate and temporary files are to be kept for debugging.''')
    args = parser.parse_args()
    return args

def get_bedisoform_info(bedisofile):
    isoforms = {}
    gene_to_isoforms, gene_to_all_exons = {}, {}
    gene_to_chrom = {}
    for bed in BedReader(bedisofile, bedClass=FlairBed):
        # ignoring fusion transcripts for now
        if bed.transcript_class != 'fusion':
            isoforms[bed.name] = bed
            if bed.gene_id not in gene_to_isoforms:
                gene_to_isoforms[bed.gene_id] = []
                gene_to_all_exons[bed.gene_id] = set()
                gene_to_chrom[bed.gene_id] = bed.chrom
            gene_to_isoforms[bed.gene_id].append(bed.name)
            for exon in bed.blocks:
                gene_to_all_exons[bed.gene_id].add(exon)
    return isoforms, gene_to_isoforms, gene_to_all_exons, gene_to_chrom

def load_read_maps(read_map_files):
    read_to_isoform = {}
    for label, mapfile in read_map_files:
        for line in open(mapfile):
            iso, reads = line.rstrip().split('\t', 2)
            for read in reads.split(','):
                read_to_isoform[(label, read)] = iso
    return read_to_isoform

def load_bam_file_for_region(bam, bam_label, gene_id, rchrom, rstart, rend, my_vars, genome, readvarinfo_to_reads, read_to_isoform, isoforms):
    with pysam.AlignmentFile(bam, 'rb') as bam:
        for a in bam.fetch(rchrom, rstart, rend):
            if a.is_mapped and not a.is_secondary and not a.is_supplementary:
                if (bam_label, a.query_name) in read_to_isoform:
                    read_iso_id = read_to_isoform[(bam_label, a.query_name)]
                    read_gene_id = isoforms[read_iso_id].gene_id
                    if read_gene_id == gene_id:
                        introns, insertions, deletions = vp.parse_cigar_for_introns_indels(a.cigartuples, a.reference_start)
                        read_id, read_vars = vp.load_bam_read_vars(a, bam_label, deepcopy(my_vars), genome, insertions, deletions)
                        if read_vars is not None:
                            if read_vars not in readvarinfo_to_reads:
                                readvarinfo_to_reads[read_vars] = set()
                            readvarinfo_to_reads[read_vars].add(read_id)

def load_bam_files_for_region(bam, norm_bam, gene_id, gene_chrom, gene_start, gene_end, my_vars, genome, read_to_isoform, isoforms):
    readvarinfo_to_reads = {}
    load_bam_file_for_region(bam, 't', gene_id, gene_chrom, gene_start, gene_end, my_vars, genome, readvarinfo_to_reads, read_to_isoform, isoforms)
    if norm_bam is not None:
        load_bam_file_for_region(norm_bam, 'n', gene_id, gene_chrom, gene_start, gene_end, my_vars, genome, readvarinfo_to_reads, read_to_isoform, isoforms)
    return readvarinfo_to_reads

def group_alleles_by_iso(file_to_read_to_allele_group, read_to_isoform, index_to_allele_group_info):
    # Isoform + allele group to reads
    isoform_to_allele_group_to_reads = {}
    gene_to_tot_reads_from_allele_groups = {}
    for label in file_to_read_to_allele_group:
        for read in file_to_read_to_allele_group[label]:
            iso_id = read_to_isoform[(label, read)]
            allele_group = file_to_read_to_allele_group[label][read]
            file_to_read_to_allele_group[label][read] = iso_id + '|' + allele_group
            gene_id = index_to_allele_group_info[allele_group]['gene']
            if gene_id not in gene_to_tot_reads_from_allele_groups:
                gene_to_tot_reads_from_allele_groups[gene_id] = {'t': 0, 'n': 0}
            if iso_id not in isoform_to_allele_group_to_reads:
                isoform_to_allele_group_to_reads[iso_id] = {}
            if allele_group not in isoform_to_allele_group_to_reads[iso_id]:
                isoform_to_allele_group_to_reads[iso_id][allele_group] = {'t': set(), 'n': set()}
            gene_to_tot_reads_from_allele_groups[gene_id][label] += 1
            isoform_to_allele_group_to_reads[iso_id][allele_group][label].add(read)
    return isoform_to_allele_group_to_reads, gene_to_tot_reads_from_allele_groups

def get_no_var_iso_info(isoform_to_allele_group_to_reads, read_to_isoform):
    # for isoforms/genes with no variants, cannot be allelotyped
    no_var_isoforms_to_reads = {}
    for (label, read), isoform in read_to_isoform.items():
        if isoform not in isoform_to_allele_group_to_reads:
            if isoform not in no_var_isoforms_to_reads:
                no_var_isoforms_to_reads[isoform] = {'t': set(), 'n': set()}
            no_var_isoforms_to_reads[isoform][label].add(read)
    return no_var_isoforms_to_reads

def write_file_headers(fh_counts, fh_map, norm_bam, generate_map):
    outline = ['#gene', 'source_isoform', 'allele_group', 'allele_labeled_isoform', 'aaseq_id', 'tumor']
    if norm_bam is not None:
        outline.append('normal')
    fh_counts.write('\t'.join(outline) + '\n')
    if generate_map:
        fh_map.write('\t'.join(outline) + '\n')

def identify_cds_pos(isoform):
    cds_start_genomic, new_cds_start = None, 0
    if isoform.thickStart != isoform.thickEnd:
        if isoform.strand == '+':
            cds_start_genomic = isoform.thickStart
        else:
            cds_start_genomic = isoform.thickEnd
        for block in isoform.blocks:
            if isoform.strand == '+':
                if block.end < isoform.thickStart:
                    new_cds_start += block.end - block.start
                elif block.start <= isoform.thickStart:
                    new_cds_start += isoform.thickStart - block.start
                    break
            else:
                if block.start > isoform.thickEnd:
                    new_cds_start += block.end - block.start
                elif block.end >= isoform.thickEnd:
                    new_cds_start += block.end - isoform.thickEnd
    return cds_start_genomic, new_cds_start

def identify_nmd_pos(isoform):
    nmd_pos_genomic, new_nmd_pos = None, 0
    if isoform.thickStart != isoform.thickEnd:
        if len(isoform.blocks) > 1:
            if isoform.strand == '+':
                nmd_pos_genomic = isoform.blocks[-2].end
                new_nmd_pos = sum([b.end - b.start for b in isoform.blocks[:-1]])
                second_last_length = isoform.blocks[-2].end - isoform.blocks[-2].start
            else:
                nmd_pos_genomic = isoform.blocks[1].start
                new_nmd_pos = sum([b.end - b.start for b in isoform.blocks[1:]])
                second_last_length = isoform.blocks[1].end - isoform.blocks[1].start
            if second_last_length < 55:
                new_nmd_pos -= second_last_length
                if len(isoform.blocks) > 2:
                    nmd_pos_genomic = isoform.blocks[-3].end if isoform.strand == '+' else isoform.blocks[2].start
                else:
                    nmd_pos_genomic = isoform.blocks[-2].start if isoform.strand == '+' else isoform.blocks[1].end
            else:
                new_nmd_pos -= 55
                if isoform.strand == '+':
                    nmd_pos_genomic -= 55
                else:
                    nmd_pos_genomic += 55
    return nmd_pos_genomic, new_nmd_pos

def get_vars_overlapping_block(block, allele_group_vars):
    block_vars = []
    for chrom, pos, ref, alt in allele_group_vars:
        if block.start <= pos <= block.end:
            block_vars.append((chrom, pos, ref, alt))
    return block_vars

def adjust_seq_with_vars(block, strand, block_vars, block_new_seq_complex, cds_start_genomic, new_cds_start, nmd_pos_genomic, new_nmd_pos):
    # reverse sort so that adding vars doesn't impact index of next vars
    block_vars.sort(reverse=True)
    for chrom, pos, ref, alt in block_vars:
        before, var_seq, after = block_new_seq_complex[:pos - block.start], block_new_seq_complex[pos - block.start:(pos - block.start) + len(ref)], block_new_seq_complex[(pos - block.start) + len(ref):]
        block_new_seq_complex = before + [[x, var_seq[0][1], None] for x in alt] + after

        if cds_start_genomic is not None:
            if (strand == '+' and pos < cds_start_genomic) or (strand == '-' and pos > cds_start_genomic):
                new_cds_start += len(alt) - len(ref)
        if nmd_pos_genomic is not None:
            if (strand == '+' and pos < nmd_pos_genomic) or (strand == '-' and pos > nmd_pos_genomic):
                new_nmd_pos += len(alt) - len(ref)
    return block_new_seq_complex, new_cds_start, new_nmd_pos

def get_iso_seq_with_vars(isoform, allele_group_vars, genome, cds_start_genomic, new_cds_start, nmd_pos_genomic, new_nmd_pos):
    this_iso_vars = []
    new_seq_complex = []
    for block in isoform.blocks:
        block_vars = get_vars_overlapping_block(block, allele_group_vars)
        block_ref_seq = genome.fetch(isoform.chrom, block.start, block.end).upper()
        block_new_seq_complex = [[block_ref_seq[x], block.start + x, None] for x in range(len(block_ref_seq))]

        block_new_seq_complex, new_cds_start, new_nmd_pos = adjust_seq_with_vars(block, isoform.strand, block_vars, block_new_seq_complex, cds_start_genomic, new_cds_start, nmd_pos_genomic, new_nmd_pos)

        this_iso_vars.extend(block_vars)
        new_seq_complex.extend(block_new_seq_complex)
    if isoform.strand == '-':
        new_seq_complex = new_seq_complex[::-1]
        for i in range(len(new_seq_complex)):
            new_seq_complex[i][0] = COMPBASE[new_seq_complex[i][0]]

    return this_iso_vars, new_seq_complex, new_cds_start, new_nmd_pos

def identify_aaseq_with_vars(new_seq_complex, new_cds_start):
    aaseq = ''
    stop_index = None
    for i in range(new_cds_start, len(new_seq_complex), 3):
        if i + 3 >= len(new_seq_complex):
            break
        this_codon = ''.join([x[0] for x in new_seq_complex[i:i + 3]])
        if i == 0 and this_codon != 'ATG':
            break
        this_aa = CODON_TABLE[this_codon]
        if this_aa == '_':
            stop_index = i + 2
            break
        aaseq += this_aa
        for j in range(i, i + 3):
            new_seq_complex[j][2] = this_aa
    return aaseq, stop_index

def update_isoform_productivity_aaseq(new_isoform, aaseq, new_seq_complex, stop_index, new_nmd_pos, aaseq_to_id, aaseq_count):
    if aaseq == '':
        new_isoform.productivity = 'NGO'
        new_isoform.aaseq_id = None
        new_isoform.thickStart = new_isoform.chromStart
        new_isoform.thickEnd = new_isoform.chromStart
    elif stop_index is None:
        new_isoform.productivity = 'NST'
        new_isoform.aaseq_id = None
        if new_isoform.strand == '+':
            new_isoform.thickEnd = new_isoform.chromEnd
        else:
            new_isoform.thickStart = new_isoform.chromStart
    else:
        if stop_index < new_nmd_pos:
            new_isoform.productivity = 'NMD'
            new_isoform.aaseq_id = None
        else:
            new_isoform.productivity = 'PRO'
            if aaseq not in aaseq_to_id:
                aaseq_to_id[aaseq] = f'FLP{aaseq_count:08d}'
                aaseq_count += 1
            new_isoform.aaseq_id = aaseq_to_id[aaseq]
        # update CDS on genome
        if new_isoform.strand == '+':
            new_isoform.thickEnd = new_seq_complex[stop_index][1]  # genomic pos at stop index
        else:
            new_isoform.thickStart = new_seq_complex[stop_index][1]
    return aaseq_count

def update_aaseq_no_vars(new_isoform, aaseq_to_id, genome, aaseq_count):
    aaseq = translate_from_bed(new_isoform, genome)
    if aaseq is not None:
        if aaseq not in aaseq_to_id:
            aaseq_to_id[aaseq] = f'FLP{aaseq_count:08d}'
            aaseq_count += 1
        new_isoform.aaseq_id = aaseq_to_id[aaseq]
    return aaseq_count

def make_var_isoform(isoform, iso_count, transcript_class=None, allele_group=None, read_support=None, gene_tot=None):
    new_isoform = deepcopy(isoform)
    new_isoform.source_isoform = isoform.name
    new_isoform.name = f'FLT{iso_count:08d}'
    iso_count += 1
    if allele_group is not None:
        new_isoform.allele_group = allele_group
    if transcript_class is not None:
        new_isoform.transcript_class = transcript_class
    if read_support is not None:
        new_isoform.read_support = read_support
    if gene_tot is not None and read_support is not None:
        new_isoform.frac_support = read_support / gene_tot
    return new_isoform, iso_count

def write_transcript_seq_no_vars(new_isoform, genome, fh_fa):
    transcript_seq = ''
    for block in new_isoform.blocks:
        transcript_seq += genome.fetch(new_isoform.chrom, block.start, block.end).upper()
    if new_isoform.strand == '-':
        transcript_seq = get_reverse_complement(transcript_seq)
    fh_fa.write(f'>{new_isoform.name}\n{transcript_seq}\n')

def write_iso_allele_counts_map(new_isoform, allele_group, iso_allele_reads, norm_bam, generate_map, fh_counts, fh_map):
    ol_aaseq = new_isoform.aaseq_id if new_isoform.aaseq_id is not None else ''
    ol = [new_isoform.gene_id, new_isoform.source_isoform, allele_group, new_isoform.name, ol_aaseq, iso_allele_reads['t']]
    if norm_bam is not None:
        ol.append(iso_allele_reads['n'])
    fh_counts.write('\t'.join(ol[:5] + [str(len(x)) for x in ol[5:]]) + '\n')
    if generate_map:
        fh_map.write('\t'.join(ol[:5] + [','.join(x) for x in ol[5:]]) + '\n')

def generate_allelotypes(args, gene_to_vars, gene_to_all_exons, gene_to_chrom, isoforms, read_to_isoform, genome):
    file_to_read_to_allele_group = {'t': {}, 'n': {}}
    index_to_allele_group_info = {}
    variant_to_allele_group_counts_info = {}
    gene_to_allele_groups = {}
    allele_group_count = 1
    # TODO can parallelize at the gene level, will need to write to intermediate files
    for gene_id in gene_to_vars:
        # only process reads if gene has variants
        # allow not spliced reads
        if len(gene_to_vars[gene_id]) > 0:
            gene_chrom, gene_start, gene_end = vp.get_gene_boundaries(gene_to_all_exons[gene_id], gene_to_chrom[gene_id])
            my_vars = vp.create_gene_vars_dict(gene_to_vars[gene_id])
            var_info, _ = vp.simplify_gene_vars(my_vars)

            # the bam file loading is slightly distinct - uses read map to filter reads
            readvarinfo_to_reads = load_bam_files_for_region(args.bam, args.norm_bam, gene_id, gene_chrom, gene_start, gene_end, my_vars, genome, read_to_isoform, isoforms)
            allele_group_to_reads = vp.process_alleotype_graph(deepcopy(readvarinfo_to_reads), args.read_support, args.frac_support)
            # don't report if there's only one final group
            if len(allele_group_to_reads) > 1:
                allele_group_count = vp.get_allele_group_info(allele_group_to_reads, allele_group_count, var_info, gene_id, gene_chrom, index_to_allele_group_info,
                                                              file_to_read_to_allele_group, variant_to_allele_group_counts_info, gene_to_allele_groups, args.norm_bam, args.read_support)
                # getting variant coverage from original assignments, not collapsed ones
                vp.get_variant_final_coverage(readvarinfo_to_reads, var_info, gene_chrom, variant_to_allele_group_counts_info)
    return file_to_read_to_allele_group, index_to_allele_group_info, variant_to_allele_group_counts_info, gene_to_allele_groups

def write_out_new_isoform(isoform, allele_group, iso_count, aaseq_count, genome, fh_bed, fh_fa, norm_bam, generate_map,
                          fh_counts, fh_map, aaseq_to_id, reads, read_sup=None, gene_tot=None, transcript_class=None, aaseq_vars=None):
    new_isoform, iso_count = make_var_isoform(isoform, iso_count,
                                              transcript_class=transcript_class,
                                              allele_group=allele_group,
                                              read_support=read_sup,
                                              gene_tot=gene_tot)
    if aaseq_vars is None:
        aaseq_count = update_aaseq_no_vars(new_isoform, aaseq_to_id, genome, aaseq_count)
    else:
        aaseq, new_seq_complex, stop_index, new_nmd_pos = aaseq_vars
        aaseq_count = update_isoform_productivity_aaseq(new_isoform, aaseq, new_seq_complex, stop_index, new_nmd_pos, aaseq_to_id, aaseq_count)
    new_isoform.write(fh_bed)
    write_transcript_seq_no_vars(new_isoform, genome, fh_fa)
    write_iso_allele_counts_map(new_isoform, allele_group, reads, norm_bam, generate_map, fh_counts, fh_map)
    return iso_count, aaseq_count

def write_out_isoform_allele_groups(isoforms, isoform_to_allele_group_to_reads, allele_group_to_final_vars, gene_to_tot_reads_from_allele_groups,
                                    no_var_isoforms_to_reads, genome, fh_bed, fh_fa, fh_counts, fh_map, norm_bam, generate_map):
    iso_count = 1
    aaseq_to_id, aaseq_count = {}, 1
    for iso_id, isoform in isoforms.items():
        if iso_id in isoform_to_allele_group_to_reads:
            for allele_group in isoform_to_allele_group_to_reads[iso_id]:
                allele_group_vars = allele_group_to_final_vars[allele_group]
                if len(allele_group_vars) > 0:
                    # identify what vars actually overlap with isoform
                    cds_start_genomic, new_cds_start = identify_cds_pos(isoform)
                    nmd_pos_genomic, new_nmd_pos = identify_nmd_pos(isoform)
                    this_iso_vars, new_seq_complex, new_cds_start, new_nmd_pos = get_iso_seq_with_vars(isoform, allele_group_vars, genome, cds_start_genomic, new_cds_start, nmd_pos_genomic, new_nmd_pos)
                    if cds_start_genomic is not None:
                        aaseq, stop_index = identify_aaseq_with_vars(new_seq_complex, new_cds_start)

                    iso_count, aaseq_count = write_out_new_isoform(isoform, allele_group, iso_count, aaseq_count, genome, fh_bed, fh_fa, norm_bam, generate_map,
                                                                   fh_counts, fh_map, aaseq_to_id,
                                                                   reads=isoform_to_allele_group_to_reads[isoform.name][allele_group],
                                                                   read_sup=len(isoform_to_allele_group_to_reads[iso_id][allele_group]['t']),
                                                                   gene_tot=gene_to_tot_reads_from_allele_groups[isoform.gene_id]['t'],
                                                                   transcript_class='with_vars',
                                                                   aaseq_vars=(aaseq, new_seq_complex, stop_index, new_nmd_pos))

                else:  # no variants on this specific allele group
                    iso_count, aaseq_count = write_out_new_isoform(isoform, allele_group, iso_count, aaseq_count, genome, fh_bed, fh_fa, norm_bam, generate_map,
                                                                   fh_counts, fh_map, aaseq_to_id,
                                                                   reads=isoform_to_allele_group_to_reads[isoform.name][allele_group],
                                                                   read_sup=len(isoform_to_allele_group_to_reads[iso_id][allele_group]['t']),
                                                                   gene_tot=gene_to_tot_reads_from_allele_groups[isoform.gene_id]['t'],
                                                                   transcript_class='with_vars')

        else:  # no variants at all on isoform/gene
            iso_count, aaseq_count = write_out_new_isoform(isoform, '', iso_count, aaseq_count, genome, fh_bed, fh_fa, norm_bam, generate_map,
                                                           fh_counts, fh_map, aaseq_to_id,
                                                           reads=no_var_isoforms_to_reads[isoform.name])
    return aaseq_to_id

def write_aaseq_key(output, aaseq_to_id):
    with open(output + '.aaseq.allelegroups.tsv', 'w') as fh:
        fh.write('aaseq_id\taaseq\n')
        for aaseq, id in aaseq_to_id.items():
            fh.write(f'{id}\t{aaseq}\n')


def getvariants():
    args = parse_args()
    print('loading genes and variants')
    genome = pysam.FastaFile(args.genome)
    my_vcfs = [args.vcf, args.norm_vcf] if args.norm_vcf is not None else [args.vcf]
    vartoalt = vp.combine_vcf_files(my_vcfs)
    chrom_to_region_to_vars = vp.reorganize_vars(vartoalt)

    # distinct - load genes and isoforms from bed
    isoforms, gene_to_isoforms, gene_to_all_exons, gene_to_chrom = get_bedisoform_info(args.isoform_bed)

    gene_to_vars = vp.get_gene_to_all_vars(gene_to_all_exons, chrom_to_region_to_vars, gene_to_chrom)

    my_read_maps = [('t', args.read_map)]
    if args.norm_read_map is not None:
        my_read_maps.append(('n', args.norm_read_map))
    read_to_isoform = load_read_maps(my_read_maps)
    # tempdir = make_temp_dir(args.output)

    print('loading bam files and creating allele groups')
    file_to_read_to_allele_group, index_to_allele_group_info, variant_to_allele_group_counts_info, gene_to_allele_groups = generate_allelotypes(args, gene_to_vars, gene_to_all_exons, gene_to_chrom, isoforms, read_to_isoform, genome)

    print('writing vcf file')
    new_header = vp.generate_new_vcf_header(args.vcf, args.norm_bam)
    allele_group_to_final_vars = vp.write_vcf_file(args.output, new_header, variant_to_allele_group_counts_info, args.norm_bam, gene_to_allele_groups)

    print('grouping alleles by isoform and getting protein predictions')
    isoform_to_allele_group_to_reads, gene_to_tot_reads_from_allele_groups = group_alleles_by_iso(file_to_read_to_allele_group, read_to_isoform, index_to_allele_group_info)
    no_var_isoforms_to_reads = get_no_var_iso_info(isoform_to_allele_group_to_reads, read_to_isoform)

    with open(args.output + '.isoforms.allelegroups.bed', 'w') as fh_bed, \
         open(args.output + '.isoforms.allelegroups.fa', 'w') as fh_fa, \
         open(args.output + '.isoforms.allelegroups.counts.tsv', 'w') as fh_counts, \
         open(args.output + '.isoforms.allelegroups.read.map.tsv', 'w') if args.generate_map is not None else None as fh_map:
        write_file_headers(fh_counts, fh_map, args.norm_bam, args.generate_map)
        aaseq_to_id = write_out_isoform_allele_groups(isoforms, isoform_to_allele_group_to_reads, allele_group_to_final_vars, gene_to_tot_reads_from_allele_groups,
                                                      no_var_isoforms_to_reads, genome, fh_bed, fh_fa, fh_counts, fh_map, args.norm_bam, args.generate_map)

    make_big_bed(genome, args.output + 'chrom.sizes', args.output + '.isoforms.allelegroups')
    write_aaseq_key(args.output, aaseq_to_id)
    if args.annotate_bams:
        print('labeling bam files')
        vp.label_bam_files(args.bam, args.norm_bam, args.output, file_to_read_to_allele_group)


if __name__ == "__main__":
    getvariants()
